name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    types: [completed]
    workflows: [Test]
    branches: [main]
  release:
    types: [published]


jobs:
#  debug-info:
#    runs-on: ubuntu-latest
#    name: Print Debug Info
#    environment: dev
#    steps:
#      - run: echo '${{ toJSON(github.event) }}'
  deploy-dev:
    name: Deploy to Dev
    if: (github.event.workflow_run && github.event.workflow_run.conclusion == 'success')
    uses: ./.github/workflows/build-deploy-common.yml
    secrets: inherit
    with:
      stack: dev
      image_tag: ${{github.sha}}
      eks_role_arn: arn:aws:iam::016272216798:role/delfi-eks-k8s-clusterrole
      eks_cluster_name: lis-dev-eks-cluster-4c2d8c8
  deploy-stage:
    name: Deploy to Stage
    if: github.event.release && github.event.release.prerelease
    uses: ./.github/workflows/build-deploy-common.yml
    secrets: inherit
    with:
      stack: stage
      image_tag: "${{github.event.release.tag_name}}_${{github.sha}}"
      version: ${{github.event.release.tag_name}}
      eks_role_arn: arn:aws:iam::016272216798:role/lis-stage-eks-github-clusterrole
      eks_cluster_name: lis-stage-eks-cluster-f077d8e
  deploy-prod:
    name: Deploy to Prod
    if: github.event.release && !github.event.release.prerelease
    uses: ./.github/workflows/build-deploy-common.yml
    secrets: inherit
    with:
      stack: prod
      image_tag: "${{github.event.release.tag_name}}_${{github.sha}}"
      version: ${{github.event.release.tag_name}}
      eks_role_arn: arn:aws:iam::016272216798:role/lis-github-actions-prod
      eks_cluster_name: lis-prod-eks-cluster-2826977
